Add a few utilities to main.js
N8python/potatoz2 pull request #3
Opened 2019-05-04 03:45 UTC by Duncan93

Introduces the following changes:
* Offers `todo`s for future changes and best-practice suggestions
* Refactors the repeated `localStore` chunk into a function that takes an object
* Refactors _some_ of the repeated jQuery calls using a new class called `JQueryHandler`. This provides a number of utility functions that leverage [rest parameters](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/rest_parameters) to allow variable numbers of parameters, which should help keep the code more concise.
  * One of these is used to update HTML values during your interval. Whereas today your HTML would look like

```html
<h5 id="patchesAmount">Patches: 0</h5>
<button id="buyAPatch" class="w3-button w3-text-white w3-grey w3-hover-lightgrey">Buy a patch for 50 potatoes.</button>
<p id="patchMax">Patch Max: 5</p>
```
and your JS
```js
$("#buyAPatch").html(`Buy a patch for ${format(patchPrice)} potatoes.`);
$("#patchesAmount").html(`Patches: ${format(patches)}`);
$("#patchMax").html(`Patch Max: ${format(patchMax)}`);
```

now the same thing can be written as
```html
<h5 id="patchesAmount">Patches: <span>0</span></h5>
<button id="buyAPatch" class="w3-button w3-text-white w3-grey w3-hover-lightgrey">Buy a patch for <span>50</span> potatoes.</button>
<p id="patchMax">Patch Max: <span>5</span></p>
```
and
```js
jqueryHelper.setSpanValues(
        [$("#buyAPatch"), format(patchPrice)],
        [$("#patchesAmount"), format(patches)],
        [$("#patchMax"), format(patchMax)],
);
```

I didn't refactor everything, but you should be able to see the additional opportunities to do so. Hopefully you'll be able to think of even more ways to abstract your logic.

2019-05-04 11:48 UTC, N8python commented
Wow - this is awesome! I have a question though - do you think the jQuery helper should be a singleton build? If we are just going to have one jQueryHelper, maybe we should have it as a standalone object.

2019-05-04 11:50 UTC, N8python requested changes
I like everything you are doing here. My only question is if jQueryHelper should be a singleton class, and not an object itself.

2019-05-04 21:30 UTC, Duncan93 commented
> I like everything you are doing here. My only question is if jQueryHelper should be a singleton class, and not an object itself.

That's a good call, but make sure to test your code frequently. Your capitalization was off.

2019-05-09 11:03 UTC, N8python commented
Most of the features this was originally meant to implement have been implemented. Therefore, is it okay if I close this request?

2019-05-10 03:02 UTC, Duncan93 commented
Sure

2019-05-11 01:19 UTC, N8python commented
The git diff has grown to large to implement your features cleanlessly. However, I'll keep in mind the advice you gave me about abstracting features in your code.

2019-05-11 01:20 UTC, N8python commented
If you want, you can resolve the git diff, make sure the code works, and then I'll merge it.

2019-05-11 22:51 UTC, Duncan93 commented
If you want people to contribute code to your projects, you should merge their PRs in a timely manner. It might be easier now for you to just pluck some code out of this PR and introduce it to your codebase. I'm not going to work anymore on this.

2019-05-12 00:10 UTC, N8python commented
Got it. I’m working on a big side project right now, but after this, I’ll introduce some of this PR into my codebase. Thanks for working on this PR.
> On May 11, 2019, at 6:51 PM, Duncan McIsaac <notifications@github.com> wrote:
> 
> If you want people to contribute code to your projects, you should merge their PRs in a timely manner. It might be easier now for you to just pluck some code out of this PR and introduce it to your codebase. I'm not going to work anymore on this.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub <https://github.com/N8python/potatoz2/pull/3#issuecomment-491549752>, or mute the thread <https://github.com/notifications/unsubscribe-auth/AKKMMKHKXYFAQULYLGVD4FLPU5EXBANCNFSM4HKYAVSQ>.
>

2019-05-12 21:56 UTC, closed without merging